name: Build WF
on:
 push:
  branches:
    -main
jobs:
 Build:
 runs-on: ubuntu-latest
 steps:
  - name: Code checkout
    uses: actions/checkout@v4

  - name: Maven Build
    run: mvn install
Testing:
runs-on: ubuntu-latest
nees: Build
steps:
  - name: Run tests on main branches
    run:mvn install

  - name: Checkstyle
    run: mvn checkstyle:checkstyle 